### PR TITLE
Mocha+Chai for tests

### PR DESCRIPTION
**Pull request by vector-of-bool**
This adds Mocha (test framework) and Chai (assertion library) to write simple tests for non-UI components.

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
How do you run the tests?

**Comment by ShaneHarvey** [comment]
Oh is it "npm test"?

**Review by ShaneHarvey — APPROVED** [review]

**Comment by vector-of-bool** [comment]
Yes, `npm test` will do it.

For posterity: The `scripts` key in `package.json` defines additional "subcommands" to Yarn/NPM. You can run the tests with `npm test`, which will invoke the `test` "script" in `package.json`, which will run `mocha out/**/*.test.js`, which executes all test suites defined in any `*.test.js` file defined under `out/`. The `tsconfig.json` was modified to emit generated JS into `out/`.

**Comment by ShaneHarvey** [comment]
npm test fails for me:
```
$  npm test

> mo@0.1.0 test
> mocha 'out/**/*.test.js'

Error: No test files found: "out/**/*.test.js"
```

**Pull request merged**
